require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "spec/dummy/db/*"
    - "spec/dummy/config/*"
    - "Dangerfile"
    - "gemfiles/*.gemfile"

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/doorkeeper/rake/*
    - doorkeeper.gemspec

Metrics/LineLength:
  Exclude:
    - spec/**/*
  Max: 100

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/TrailingBlankLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading
